# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170109_1002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoolStorage',
        ),
    ]
